# Generated by Django 4.2.20 on 2025-07-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=10)),
                ('expressions_detectees', models.TextField()),
                ('publication_date', models.DateField()),
                ('source_code', models.CharField(max_length=50)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('nom_source', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FactivaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_source', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('code_source', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('content', models.TextField()),
            ],
        ),
    ]
